create database E_COMMERCE_BEHAVIOR;
use E_COMMERCE_BEHAVIOR;
select * from shopping_data limit 10;

#Q1.What is the total revenue generated by the business?
select concat('$',round(sum(revenue)),2) as Total_Revenue
from shopping_data;

#Q2. How many total orders were placed?
select concat('$',count(*)) as Total_Orders
from shopping_data;

#Q3.How many unique customers do we have?
select count(distinct customer_id) as Unique_Customers
from shopping_data;

#Q4. Which products are the most demanded?
select product_name,sum(quantity) as Total_quantity
from shopping_data
group by product_name
order by total_quantity desc
limit 15;

#Q5. Which product categories generate the most revenue?
select category, concat('$',round(sum(revenue),0)) as Total_Most_Revenue
from shopping_data
group by category
order by total_most_revenue desc;

#Q6. Which categories have the highest average product ratings?
select category,
round(avg(avg_rating),1) as avg_rating
from shopping_data
group by category
order by avg_rating;

#Q7. Which product generate the highest revenue?
select product_name, round(sum(revenue),2) as total_revenue
from shopping_data
group by product_name
order by total_revenue desc 
limit 10;

#Q8. What is the monthly sales trend?
select month(transaction_date) as month,
concat('$',round(sum(revenue),2)) as month_revenue
from shopping_data
group by month
order by month;

#Q9. Which products have revenue above average?
select product_name, round(sum(revenue),2)
as total_revenue
from shopping_data
group by product_name
having total_revenue > ( select avg(revenue)
							shopping_data);
 
#Q10. Find products in the top revenue category?
select product_name, category
from shopping_data
where category = (
					select category
                    from shopping_data
                    group by category
                    order by sum(revenue) desc
                    limit 1);
                    
#Q11. Find customers who purchased the most expensive product?
select distinct customer_id, product_name
from shopping_data
where price = ( 
				select max(price)
                from shopping_data);
                
#Q12. Find top 3 products in each category?
select *
from (
		select product_name, category, concat('$',round(sum(revenue),2)) as total_revenue,
        rank() over (partition by category order by sum(revenue) desc) as rank_position
        from shopping_data
        group by product_name, category) ranked
        where rank_position <= 3;
        
#Q13. find repeat customers?
select customer_id,
count(transaction_id) as purchase_count
from shopping_data
group by customer_id
having purchase_count > 1;

#Q14. Day wise highest revenue?
select * 
from (select transaction_date, sum(revenue) as daily_revenue,
		rank() over(order by sum(revenue) desc) as rank_position
        from shopping_data
        group by transaction_date) ranked
        where rank_position = 1;
